---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
  labels:
    app: fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: myservice:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
            - containerPort: 8000
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi
spec:
  ports:
  - port: 80
    name: myservice
    protocol: TCP
    targetPort: 80
  - port: 8000
    name: daemon
    protocol: TCP
    targetPort: 8000
  selector:
    app: fastapi
  type: LoadBalancer