kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: batch-jobs
rules:
  - apiGroups:
      - "batch"
    resources:
      - "*"
    verbs:
      - "*"
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: batch-jobs-role-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: batch-jobs-service-account
    namespace: default
  - kind: ServiceAccount
    name: default
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: batch-jobs
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: batch-jobs-service-account
  namespace: default